version: "3"
services:
#  elasticsearch:
#    image: elasticsearch:8.3.3
#    container_name: elasticsearch
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    cap_add:
#      - IPC_LOCK
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://elasticsearch:9200" ]
#      interval: 10s
#      timeout: 10s
#      retries: 5
#
#  kibana:
#    container_name: kibana
#    image: kibana:8.3.3
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#    volumes:
#      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#
#  logstash:
#    container_name: logstash
#    image: logstash:8.3.3
#    depends_on:
#      - elasticsearch
#    ports:
#      - "5044:5044"
#      - "50000:50000/tcp"
#      - "50000:50000/udp"
#      - "9600:9600"
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: simpleblog
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
#  go-web-server:
#    container_name: goweb
#    build: .
#    depends_on:
#      - elasticsearch
#    restart: on-failure
#    ports:
#      - "8080:8080"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
#volumes:
#  elasticsearch-data:
#    driver: local