version: "3"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: simpleblog
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
  go-web-server:
    container_name: goweb
    build: .
    environment:
      - JAEGER_SERVICE_NAME=goweb
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_REPORTER_LOG_SPANS=true
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    depends_on:
      - db
      - jaeger
    restart: on-failure
    ports:
      - "8080:8080"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"